name: Build and deploy Next.Js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "fashion-next-demo2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          npm ci
          npm install autoprefixer@^10.0.1 --save-dev

      - name: Build application
        run: npm run build

      - name: Prepare standalone build
        run: |
          cp -r .next/static .next/standalone/.next/
          cp -r public .next/standalone/

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: .next/standalone
